### ISSUE TITLE
inplace-config pyaml dependency

### ISSUE THREAD

**Issue by like-a-bause** [hicknhack-software/ansible-buildbot#1] opened 2015-06-23 10:26 UTC
starting a master failed on a ubuntu14.04 machine. pyaml should be installed as a dependency for inplace-config.

**Comment by arBmind** [comment] 2015-06-23 21:11
Thank you for reporting the issue. Unfortunately I am unable to reproduce it.
There was an issue with the YAML file loading, but it's not related to pyaml missing.

I use the latest, official "ubuntu/trusty64" vagrant boxes for testing. There no further dependencies are required.
Please try my latest pushes.

**Comment by arBmind** [comment] 2016-08-05 17:19
No progress for half a year. I close the issue, feel free to open a new issue, to find a solution.

**Closed as completed by arBmind** 2016-08-05 17:19 UTC
